### ISSUE TITLE
https certificate expired Aug. 29 2021

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [potatofarms/wvwstats#9]
The site has been inaccessible since Aug. 29 2021.

![image](https://user-images.githubusercontent.com/24264268/139293317-e3b4c34c-6253-4577-8ea8-aba80dd708aa.png)

**Comment by adekau** [comment]
Hi, thanks for letting me know. It's something I've known about for a bit, but is a bit involved for fixing.

It comes down mainly to the image the server is running on, which is Ubuntu 16 LTS on i386 which letsencrypt/certbot has dropped support for now (why the SSL problem has been here for so long). So in order to fix that I need to do a complete reinstall on a newer architecture (I'm not sure why it wasn't on 64 bit in the first place??) and transfer all the config, api scripts, database (the hard bit) to the new image.

I haven't exactly been looking forward to putting in all that effort for a website for a game I hardly play nowadays, so I hope you can forgive me for being extremely slow here. I'll attempt to get it going again though since you and a few others have asked.

**Comment by adekau** [comment]
Should be taken care of. Configured a new image for it running on Ubuntu 20 LTS amd64 and upgraded all the individual components (nginx, postgres, node, etc)
